### ISSUE TITLE
Fix unused and outdated modules

### ISSUE THREAD

**Issue by guiconti** [guiconti/Gibot#19]

**Comment by guiconti** [comment]
A gente usa Bithound que ajuda a gerenciar essas paradas de pacotes e qualidade de código, o link pro bithound do projeto é https://www.bithound.io/github/guiconti/Gibot

Precisa ir no arquivo package.json que está na root do projeto, ir na estrutura "dependencies", remover os modules não utilizados e atualizar a versão dos modules utilizados. Pra ver quais precisamos remover e atualizar vai na aba dependencies do Bithound, ele diz lá os unused e outdated.

**Comment by miaket** [comment]
cacete, genial esse bithound
