### ISSUE TITLE
Add reply markup on reddit messages

### ISSUE THREAD

**Issue by guiconti** [guiconti/Gibot#20]

**Comment by guiconti** [comment]
Essa feature foi resolvida apenas passando o objeto options na API de envio de mensagem. Quem chama essa API deve passar o options de reply markup.

**Comment by miaket** [comment]
n tendi, Isso faz parte do rankeador?

**Comment by guiconti** [comment]
Isso é a parte pra aparecer os botões embaixo de uma mensagem. Hoje uma outra aplicação (exemplo auto voter) consegue mandar mensagens pro Gibot por uma api que está em controllers/sendMessageToChat aí eu coloquei nessa API pra aceitar uma propriedade chamada options, se o cara quiser adicionar um teclado na mensagem que ele enviar no gibot ele chama a API passando o teclado em options.
