### ISSUE TITLE
adicionar ao git ignore: .vscode/settings.json (Mais pergunta do que abertura de iss)

### ISSUE THREAD

**Issue by miaket** [guiconti/Gibot#24]
.vscode/settings.json <- esse arquivo é necessário? Ele é só configuração do VSCODE ou tem coisa a mais?
Se N for vou botar no gitignore

**Comment by miaket** [comment]
@guibasconti

**Comment by miaket** [comment]
@guiconti

**Comment by guiconti** [comment]
Deve ignorar ele sim, são as configs do vscode para esse projeto. Tem que ser local isso não deve ir pro git

**Comment by miaket** [comment]
Valeu, vou por ele no .ignore entao
