### ISSUE TITLE
Remove all not used reddit code

### ISSUE THREAD

**Issue by guiconti** [guiconti/Gibot#8]

**Comment by guiconti** [comment]
@miaket Tem uns códigos que não são mais utilizados no Gibot porque migrei o reddit pra ficar separado do Gibot. Seria legal se você conseguisse identificar quais são e remover. O Gibot nasce no app/core/gibimbot.js e de lá você consegue seguir o fluxo inteiro de uma chamada pro reddit e mapear os arquivos que estão usando e ver quais são do reddit no repo que não estão sendo usados. Se quiser fazer e precisar de ajuda avisa

**Comment by miaket** [comment]
On it
